CREATE TABLE IF NOT EXISTS CATEGORY_DIM (
    ID INTEGER AUTOINCREMENT,
    NAME VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS PRODUCT_TYPE_DIM (
    ID INTEGER AUTOINCREMENT,
    NAME VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS PRODUCT_DIM (
    ID VARCHAR(200),
    TITLE VARCHAR(200),
    SUBTITLE VARCHAR(200),
    CATEGORY_ID INTEGER,
    TYPE_ID INTEGER,
    CURRENT_PRICE FLOAT,
    FULL_PRICE FLOAT
);

CREATE TABLE IF NOT EXISTS COLOR_LABEL_DIM (
    ID INTEGER AUTOINCREMENT,
    NAME VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS COLOR_DIM (
    ID VARCHAR(200),
    DISCOUNT BOOLEAN,
    LABEL_ID INTEGER
);

CREATE TABLE IF NOT EXISTS SALE_FACT (
    ID VARCHAR(200),
    AMOUNT INTEGER,
    PRODUCT_ID VARCHAR(200),
    CATEGORY_ID INTEGER,
    COLOR_ID VARCHAR(200),
    TOTAL_SALES FLOAT
);